# Generated by Django 4.0.1 on 2022-02-03 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=100)),
                ('duracion', models.CharField(default='', max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('texto', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('fecha', models.DateField()),
                ('texto', models.CharField(default='', max_length=1000)),
                ('tipo', models.CharField(choices=[('TEDX', 'tedx'), ('Patrocinio Trabajos Investigación', 'patrocinio trabajos investigación'), ('London Finance Seminar', 'london finance seminar')], default='', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
            ],
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellidos', models.CharField(default='', max_length=30)),
                ('dni', models.CharField(default='', max_length=9)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(default='', max_length=20)),
                ('texto', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaComienzo', models.DateField()),
                ('fechaFin', models.DateField(null=True)),
                ('nombre', models.CharField(default=' ', max_length=20)),
                ('apellido', models.CharField(default=' ', max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('texto', models.CharField(default='', max_length=5000)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', models.CharField(blank=True, default='', max_length=1000)),
                ('objetivo', models.CharField(blank=True, default='', max_length=1000)),
                ('dirigido', models.CharField(blank=True, default='', max_length=1000)),
                ('premio', models.CharField(default='', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='', max_length=100)),
                ('nombre', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=20)),
                ('NIF', models.CharField(default=' ', max_length=20)),
                ('tipo', models.CharField(choices=[('Persona Juridica', 'persona juridica'), ('Persona Fisica', 'persona fisica')], max_length=30)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('parte', models.CharField(blank=True, default='', max_length=100)),
                ('programa', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('coordinadores', models.ManyToManyField(to='appFLB.Coordinador')),
                ('profesor', models.ManyToManyField(to='appFLB.Profesor')),
                ('temas', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appFLB.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('sinopsis', models.CharField(blank=True, default='', max_length=2000)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
                ('autores', models.ManyToManyField(to='appFLB.Autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFLB.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='EdicionPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
                ('edicionPremio', models.CharField(default='', max_length=20)),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFLB.ganador')),
                ('jurado', models.ManyToManyField(to='appFLB.Jurado')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFLB.premio')),
            ],
        ),
        migrations.CreateModel(
            name='EdicionBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('edicionBeca', models.CharField(default='', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image')),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFLB.beca')),
                ('beneficiario', models.ManyToManyField(to='appFLB.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default=' ', max_length=30)),
                ('miembro', models.ManyToManyField(to='appFLB.Miembro')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('texto', models.CharField(blank=True, default='', max_length=1000)),
                ('tipo', models.CharField(choices=[('Cursos Varios', 'cursos varios'), ('Seminarios', 'seminarios')], default='', max_length=30)),
                ('modulo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appFLB.modulo')),
            ],
        ),
    ]
