# Generated by Django 4.0.1 on 2022-02-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0002_alter_modulo_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='temas',
        ),
        migrations.AddField(
            model_name='tema',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appFLB.modulo'),
        ),
    ]
