# Generated by Django 4.0.1 on 2022-02-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0003_remove_modulo_temas_tema_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadformacion',
            name='modulo',
        ),
        migrations.AddField(
            model_name='modulo',
            name='actividadFormacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appFLB.actividadformacion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Tedx', 'tedx'), ('Patrocinio Trabajos Investigación', 'patrocinio trabajos investigación'), ('London Finance Seminar', 'london finance seminar')], default='', max_length=50),
        ),
    ]
