# Generated by Django 4.0.1 on 2022-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0004_remove_actividadformacion_modulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadformacion',
            name='tipo',
            field=models.CharField(choices=[('Cursos Varios', 'cursos varios'), ('Seminarios', 'seminarios')], max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Tedx', 'tedx'), ('Patrocinio Trabajos Investigación', 'patrocinio trabajos investigación'), ('London Finance Seminar', 'london finance seminar')], max_length=50),
        ),
    ]
