# Generated by Django 4.0.1 on 2022-02-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0005_alter_actividadformacion_tipo_alter_evento_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
