# Generated by Django 4.0.1 on 2022-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0006_delete_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
    ]
