# Generated by Django 4.0.1 on 2022-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0007_profesor_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadformacion',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='modulo',
        ),
        migrations.AddField(
            model_name='modulo',
            name='tema',
            field=models.ManyToManyField(to='appFLB.Tema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
