# Generated by Django 4.0.1 on 2022-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0008_remove_actividadformacion_texto_remove_tema_modulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='actividadFormacion',
        ),
        migrations.AddField(
            model_name='actividadformacion',
            name='modulos',
            field=models.ManyToManyField(to='appFLB.Modulo'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='nombreApellidos',
            field=models.CharField(default='', max_length=50),
        ),
    ]
