# Generated by Django 4.0 on 2022-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0009_remove_modulo_actividadformacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='cargo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='edicionbeca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='edicionpremio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ganador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='jurado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\\img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='tipo',
            field=models.CharField(choices=[('Persona Jurídica', 'persona jurídica'), ('Persona Física', 'persona física')], max_length=30),
        ),
    ]
