# Generated by Django 4.0 on 2022-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0010_alter_autor_imagen_alter_beneficiario_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\img', verbose_name='Image'),
        ),
    ]
