# Generated by Django 4.0 on 2022-02-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0011_alter_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB\\static\x07ppFLB\\img', verbose_name='Image'),
        ),
    ]
