# Generated by Django 4.0 on 2022-02-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0014_alter_libro_imagen_alter_premio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB/img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='appFLB/img', verbose_name='Image'),
        ),
    ]
