# Generated by Django 4.0 on 2022-02-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0015_alter_libro_imagen_alter_premio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
