# Generated by Django 4.0.1 on 2022-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0017_alter_edicionbeca_fecha_alter_edicionpremio_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
