# Generated by Django 4.0.1 on 2022-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0019_alter_autor_imagen_alter_beneficiario_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='socio',
            name='NIF',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
