# Generated by Django 4.0 on 2022-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFLB', '0022_alter_libro_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='telefono',
            field=models.IntegerField(max_length=9),
        ),
    ]
